.\" $Id$
.TH SORT_DEMO 1 "August 2009"
.SH NAME
sort_demo \- sorting algorithms demo
.SH SYNOPSIS
\fBsort_demo\fR [\fIOPTION\fR]...
.br
.SH OPTIONS
This program follow the usual GNU command line syntax, with long options starting with two dashes (`-').
.TP
A summary of options is included below.
.TP
.B \-f, \-\-fullscreen
Run sort_demo in fullscreen mode.
.TP
.B \-d, \-\-datadir=\fIdir\fR
Load program's data from \fIdir\fR.
.TP
.B \-\-display=\fIdisplay\fR
Specify the X display to use.
.TP
.B \-\-help
Show summary of options.
.SH AUTHOR
This manual page was written by Sergio Perticone <g4ll0ws@gmail.com>.
